# Generated by Django 6.0.1 on 2026-08-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержимое урока'),
        ),
    ]
