# Generated by Django 6.0.1 on 2026-08-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Пользователь'), ('student', 'Студент'), ('teacher', 'Учитель')], default='user', max_length=20),
        ),
    ]
